/* ─────────────────────────────────────────
   칸칸 — blog-data.js
   새 글은 배열 맨 앞에 추가하세요.
   ───────────────────────────────────────── */

/* ── 작성자 정보 ── */
const AUTHORS = window.AUTHORS = {
  'energuard': {
    name: '에너가드컴퍼니',
    role: '자재 유통 전문 에디터',
    avatar: 'blog/authors/energuard.jpg',
  },
  'masterlee': {
    name: '마스터 리',
    role: '시공 납품 전문 에디터',
    avatar: 'blog/authors/masterlee.jpg',
  },
  'hana': {
    name: '하나',
    role: '리빙 라이프 스타일 에디터',
    avatar: 'blog/authors/hana.jpg',
  },
};

const BLOG_POSTS = window.BLOG_POSTS = [
  {
    id: 'neopor-delivery-story',
    author: 'masterlee',
    tag: '단열재',
    thumbBadge: '납품일지',
    thumbBadgeColor: '#2aaa75',
    badge: '비드법 2종 납품 현장 이야기',
    title: '가등급 단열재 네오폴(비드법 2종) 납품 현장 이야기',
    excerpt: '네오폴은 흑연이 섞인 회색 EPS입니다. 같은 두께에서 일반 EPS보다 단열 성능이 약 20% 높아 가등급 인증이 가능합니다. 이번 납품 현장에서 직접 보고 느낀 것들을 기록했습니다.',
    date: '2026.06.29',
    readTime: '4분',
    thumb: 'blog/posts/images/neopor-delivery-story_main.jpg',
  },
  {
    id: 'rainy-season-mold-tips',
    author: 'hana',
    tag: '시공팁',
    thumbBadge: '생활꿀팁',
    thumbBadgeColor: '#3b7dd8',
    badge: '장마·결로 대응 가이드',
    title: '장마철 집 관리법, 곰팡이와 습기를 줄이는 7가지 방법',
    excerpt: '장마가 시작되면 아무리 환기해도 눅눅한 느낌이 사라지지 않고 어느 순간 검은 점이 생깁니다. 곰팡이는 한 번 자리 잡으면 제거도 까다롭습니다. 장마철에 실천할 수 있는 관리법 7가지를 정리했습니다.',
    date: '2026.06.29',
    readTime: '6분',
    thumb: 'blog/posts/images/rainy-season-mold-tips_main.jpg',
  },
  {
    id: 'insulation-types-guide',
    author: 'energuard',
    tag: '단열재',
    thumbBadge: '단열재',
    badge: '단열재 종류·특성 비교',
    title: '단열재 종류 총정리 — 미네랄울부터 PF보드까지 핵심 비교',
    excerpt: '미네랄울, 비드법, 압출법, 경질우레탄, PF보드까지 — 현장에서 자주 쓰이는 단열재 8종의 특성과 적용 부위를 한눈에 정리했습니다. 종류가 많아 헷갈릴 때 기준이 되는 비교 가이드입니다.',
    date: '2026.06.30',
    readTime: '10분',
    thumb: 'blog/posts/images/insulation-types-guide_main.jpg',
  },
  {
    id: 'insulation-thickness-guide',
    author: 'energuard',
    tag: '단열재',
    thumbBadge: '단열재',
    badge: '지역별·부위별 두께 기준',
    title: '단열재 두께, 어떻게 결정해야 하나요? 지역별·부위별 기준 총정리',
    excerpt: '중부1지역 외벽 최소 열관류율은 0.150 W/㎡K. 이 숫자 하나가 단열재 두께를 결정합니다. 실무에서 자주 묻는 두께 계산 로직을 정리했습니다.',
    date: '2026.06.15',
    readTime: '8분',
    thumb: null,
  },
  {
    id: 'detached-house-insulation-guide',
    author: 'energuard',
    tag: '단열재',
    thumbBadge: '단열재',
    badge: '신축·리모델링 단열 선택 가이드',
    title: '단독주택 단열, 처음 설계부터 방향을 잡아야 합니다',
    excerpt: '단열은 한 번 시공하면 나중에 바꾸기 매우 어렵습니다. 신축 단독주택이라면 내단열과 외단열 중 어느 쪽을 선택하느냐가 집의 쾌적함을 평생 좌우합니다. 결로와 열교, 비용까지 고려한 선택 기준을 정리했습니다.',
    date: '2026.06.30',
    readTime: '5분',
    thumb: 'blog/posts/images/detached-house-insulation-guide_main.jpg',
  },
  {
    id: 'reflective-insulation-how-to',
    author: 'energuard',
    tag: '단열재',
    thumbBadge: '단열재',
    badge: '에어갭 시공 핵심 정리',
    title: '열반사 단열재 제대로 붙이는 법 — 에어갭 없으면 반사 효과 0입니다',
    excerpt: '열반사 단열재는 공기층이 핵심입니다. 밀착 시공하면 일반 발포 단열재와 성능 차이가 거의 없어요. 올바른 시공 방법과 흔한 실수를 짚었습니다.',
    date: '2026.05.30',
    readTime: '7분',
    thumb: null,
  },
  {
    id: 'self-interior-insulation-checklist',
    author: 'energuard',
    tag: '셀프인테리어',
    thumbBadge: '단열재',
    badge: '셀프 시공 체크리스트',
    title: '셀프 단열 공사 전에 체크해야 할 것 7가지',
    excerpt: '자재비 아끼려고 직접 하다가 오히려 비용이 더 드는 경우가 있습니다. 직접 해도 되는 공정과 전문가 맡겨야 할 공정을 구분하는 기준을 정리했습니다.',
    date: '2026.05.22',
    readTime: '6분',
    thumb: null,
  },
  {
    id: 'foam-spray-usage-tips',
    author: 'energuard',
    tag: '단열재',
    thumbBadge: '단열재',
    badge: '불연·준불연·난연 단열재 가이드',
    title: '불연·준불연·난연 차이, 불에 안타는 단열재는 무엇?',
    excerpt: '화재 안전 등급이 왜 중요한지, 불연·준불연·난연은 어떻게 다른지 — 최근 대형 화재 사례와 건축법 기준까지 함께 정리했습니다.',
    date: '2026.06.30',
    readTime: '6분',
    thumb: null,
  },
];